### ISSUE TITLE
Sha3 dependency problem

### ISSUE THREAD

**Issue by Octet83** [ambrosus/ambrosus-node#154]
Hi,

I'm trying to run a node but I have one problem with yarn install command with Sha3 dependency 

```
sha3.target.mk:99: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/var/www/amb_node/ambrosus-node/node_modules/keccakjs/node_modules/sha3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.9.78-xxxx-std-ipv6-64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/amb_node/ambrosus-node/node_modules/keccakjs/node_modules/sha3
```

Am I alone ?

**Comment by marekkirejczyk** [comment]
Possibly related to [this issue](https://github.com/phusion/node-sha3/issues/32). 
You can try to downgrade node to v9.3.0 to verify this.

**Comment by Octet83** [comment]
Yes, that's OK with 9.3.0, thanks
